### ISSUE TITLE
Fiddler not accepting custom rules

### ISSUE THREAD

**Issue by CaptainDemozan** [SpudMonkey7k/neopets-flash-shockwave-3dvia-fix#1]
I tried to enter the custom rules into Fiddler (Since putting the .js script didn't seem to work), and it's not accepting the script. It gives me this error:

> FiddlerScript compilation failed on line 1
> (start-of-file)
> ERROR LINE --> import System
> import System.Windows.Forms
>Invalid character
>ErrorSeverity: 0

I'm thinking this error is why Shockwave games do not work for me (Hannah and Gourmet Bowls don't load, and while Attack of the Slorgs does, starting the game isn't possible). How do I fix this?

**Comment by SpudMonkey7k** [comment]
sorry for the late reply, just noticed that i had a notification. 

so placing the customrules.js file in documents/fiddler2/scripts doesn't work? 
im not sure why pasting the code in the custom rules window isn't working for you either. 

which version of fiddler classic are you using?
